# Read the Docs configuration file for Sphinx projects
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# Required
version: 2

submodules:
  include: all

# Set the OS, Python version and other tools you might need
build:
  os: ubuntu-22.04
  tools:
    python: "3.11"
    
# Build documentation in the "docs/" directory with Sphinx
sphinx:
  configuration: dynex/docs.py
  builder: html

python:
   version: 3.11
   install:
      - method: pip
        path: .
        extra_requirements: [all]
      - requirements: docs/requirements.txt
